### ISSUE TITLE
 The color of the image sequence seen in the Davinci interface is different from the color seen when loaded into OpenVPCal.

### ISSUE THREAD

**Issue by haoxiaoshuai01** [Netflix/OpenVPCal#53]
**Describe the bug**

The color of the image sequence seen in the Davinci interface is different from the color seen when loaded into OpenVPCal.
Is it possible that the inaccuracy of the final color calibration result is due to the aforementioned reason?

**To Reproduce**

1 UE media player plays the image sequence, and the video format captured by the camera is .avi. The camera's color space is BT.709.
2 The color setting in DaVinci is set to ACEScct. no input transform no output transform
3 The image color in DaVinci is different from that in OpenVPCal.
4 The calibration result is incorrect.

**Screenshots**

![File](https://github.com/Netflix/OpenVPCal/assets/42887640/f1995929-dedb-4530-988b-6c3257f1bcf3)
![image](https://github.com/Netflix/OpenVPCal/assets/42887640/0600f2d9-4993-401f-82ed-06783db3876a)

**Version (please complete the following information):**
openvpcal v1.1.0

**Comment by giardiello** [comment]
Hello,Thanks Adam for following up. Can I also add to what Adam said, why are you saying that the calibration is incorrect? I only see that the software cannot find the Macbeth chart (mostly due to the low tolerance we have on the color chart checker, we are going to update it).Have you actually run and load the calibration in Unreal and run the tool again with the verify wall?Try to reduce the defocus for now.Also, if the input file is an Avi, can you clarify what camera are we talking about here? Does it have an input color space? Setting Davinci in no input color space implies that the file is raw. Are you applying an IDT?FOn 7 Jun 2024 13:24, davisadam10 ***@***.***> wrote:
The difference in the view is nothing to do with the calibration. The image selection window is only used for selection of the region of interest.
It applies a simple colour version to the display to "sRGB - Display" which probably differs from what you have set in da vinchi.
The analysis section is colour managed allowing the user to set the display how they wish, we could look to expose this in future to the image selection widget but given its only for selecting images and not colour critical its lower prio.
As for why the calibration is wrong, are you using Unreal Engine for playback here? Have you ensured the colour pipeline and post processing effects in unreal are all configured correctly?
Similarly what wall are you calibrating that has a peak luminance of 100 nits?
Could you supply some more details about your setup?

**Comment by haoxiaoshuai01** [comment]
Thank you, Adam and Giardiello, for your replies. Over the past few days, I have reviewed the User Guide and identified some mistakes in my previous operations:

   1 I did not apply the OCIO transformation in UE.
   2 The LED's color space and peak luminance in nits were not accurately determined. I had previously entered incorrect values. The LED manufacturer told me that it supports the sRGB space with a peak luminance of 600 nits. I think I should buy an instrument to determine the exact values.

Regarding the camera capture process, I'm not sure if it was done correctly. The camera is a Sony FX9 connected to a Blackmagic video card. The camera is set to HDR conversion to Rec.709 color space. The video format obtained from Blackmagic Media Express is .avi, which is then loaded into DaVinci.

It was hasty of me to raise some questions without thoroughly reviewing the User Guide and running the tests. I will review the tests again.
